development:
  dialect: postgres
  database: coinssh_development
  user: {{envOr "DATABASE_USER" "postgres"}}
  password: {{envOr "DATABASE_PASSWORD" "root"}}
  host: {{envOr "DATABASE_HOSTNAME" "127.0.0.1"}}
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:root@127.0.0.1:5432/coinssh_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:root@127.0.0.1:5432/coinssh_production?sslmode=disable"}}